import 'package:flutter/material.dart';
import 'package:flutter_swipes/src/core/theme/app_theme.dart';
import 'package:google_fonts/google_fonts.dart';

/// App Store / user transparency for generative AI.
const kAiProviderLabel = 'Llama 3.3 (via Groq)';
const kAiProviderFallbacks = 'Google Gemini, Moonshot & MiniMax';

const kAiProviderBubbleLabels = <String, String>{
  'groq': 'Groq · Llama 3.3',
  'gemini': 'Google Gemini',
  'kimi': 'Moonshot Kimi',
  'minimax': 'MiniMax',
};

String aiProviderBubbleLabel(String? provider) =>
    kAiProviderBubbleLabels[provider ?? ''] ?? kAiProviderBubbleLabels['groq']!;

enum AiDisclosureVariant { compact, roomy }

class AiDisclosure extends StatelessWidget {
  const AiDisclosure({
    super.key,
    required this.isLight,
    this.variant = AiDisclosureVariant.compact,
    this.showModelLine = false,
  });

  final bool isLight;
  final AiDisclosureVariant variant;
  final bool showModelLine;

  Color get _muted => isLight ? Colors.black45 : Colors.white;
  Color get _ink => isLight ? const Color(0xFF0A0A0D) : Colors.white;

  @override
  Widget build(BuildContext context) {
    if (variant == AiDisclosureVariant.roomy) {
      return Container(
        width: double.infinity,
        padding: const EdgeInsets.fromLTRB(14, 12, 14, 14),
        decoration: BoxDecoration(
          color: isLight
              ? Colors.black.withAlpha(8)
              : Colors.white.withAlpha(10),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(
            color: isLight ? Colors.black.withAlpha(26) : Colors.white,
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(
                  Icons.auto_awesome_rounded,
                  size: 14,
                  color: AppTheme.brandPrimary,
                ),
                const SizedBox(width: 8),
                Text(
                  'Powered by AI',
                  style: GoogleFonts.plusJakartaSans(
                    color: isLight ? _ink.withAlpha(200) : Colors.white,
                    fontWeight: FontWeight.w800,
                    fontSize: 12,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Text.rich(
              TextSpan(
                style: GoogleFonts.plusJakartaSans(
                  color: _muted,
                  fontSize: 11,
                  height: 1.45,
                ),
                children: [
                  const TextSpan(
                    text: 'Replies are generated by artificial intelligence — primarily ',
                  ),
                  TextSpan(
                    text: kAiProviderLabel,
                    style: GoogleFonts.plusJakartaSans(
                      color: isLight ? _ink.withAlpha(210) : Colors.white,
                      fontWeight: FontWeight.w700,
                      fontSize: 11,
                    ),
                  ),
                  TextSpan(
                    text:
                        ', with secure fallbacks ($kAiProviderFallbacks). Content may be inaccurate and includes third-party business data. Swipess and Apple are not responsible for the accuracy of AI recommendations or business interactions. Not a substitute for professional legal or financial advice. Only your chat messages are sent to AI providers — not your password or payment data.',
                  ),
                ],
              ),
            ),
          ],
        ),
      );
    }

    final line = showModelLine
        ? 'AI · $kAiProviderLabel · Gemini & MiniMax fallbacks · Apple & Swipess are not liable for 3rd-party business data or AI errors.'
        : 'AI-powered · Apple & Swipess are not liable for 3rd-party business data or AI errors.';

    return Row(
      children: [
        Icon(Icons.auto_awesome_rounded, size: 11, color: _muted),
        const SizedBox(width: 5),
        Expanded(
          child: FittedBox(
            fit: BoxFit.scaleDown,
            alignment: Alignment.centerLeft,
            child: Text(
              line,
              maxLines: 1,
              style: GoogleFonts.plusJakartaSans(
                color: _muted,
                fontSize: 9.5,
                fontWeight: FontWeight.w600,
                letterSpacing: 0.05,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
