create table if not exists public.video_playback_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  user_id uuid null,
  listing_id uuid null references public.listings(id) on delete set null,
  event_type text not null check (event_type in ('init','first_frame','rebuffer','playback_error','ended','prefetch')),
  surface text not null default 'quick_filter',
  platform text not null,
  network_type text null,
  media_url_hash text null,
  init_ms integer null,
  ttff_ms integer null,
  buffer_ms integer null,
  rebuffer_count integer null,
  position_ms integer null,
  duration_ms integer null,
  error_code text null,
  extra jsonb not null default '{}'::jsonb
);

alter table public.video_playback_events enable row level security;
revoke all on public.video_playback_events from anon, authenticated;

create index if not exists video_playback_events_created_at_idx
  on public.video_playback_events(created_at desc);
create index if not exists video_playback_events_listing_created_idx
  on public.video_playback_events(listing_id, created_at desc);
create index if not exists video_playback_events_platform_event_idx
  on public.video_playback_events(platform, event_type, created_at desc);

create or replace function public.record_video_playback_event(
  p_session_id text,
  p_event_type text,
  p_listing_id uuid default null,
  p_surface text default 'quick_filter',
  p_platform text default 'unknown',
  p_network_type text default null,
  p_media_url_hash text default null,
  p_init_ms integer default null,
  p_ttff_ms integer default null,
  p_buffer_ms integer default null,
  p_rebuffer_count integer default null,
  p_position_ms integer default null,
  p_duration_ms integer default null,
  p_error_code text default null,
  p_extra jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_event_type not in ('init','first_frame','rebuffer','playback_error','ended','prefetch') then
    raise exception 'invalid_event_type';
  end if;
  if coalesce(length(p_session_id),0) < 8 or length(p_session_id) > 120 then
    raise exception 'invalid_session_id';
  end if;

  insert into public.video_playback_events(
    session_id,user_id,listing_id,event_type,surface,platform,network_type,media_url_hash,
    init_ms,ttff_ms,buffer_ms,rebuffer_count,position_ms,duration_ms,error_code,extra
  ) values (
    left(p_session_id,120),auth.uid(),p_listing_id,p_event_type,left(coalesce(p_surface,'quick_filter'),80),
    left(coalesce(p_platform,'unknown'),80),left(coalesce(p_network_type,''),80),left(coalesce(p_media_url_hash,''),128),
    case when p_init_ms is null then null else greatest(p_init_ms,0) end,
    case when p_ttff_ms is null then null else greatest(p_ttff_ms,0) end,
    case when p_buffer_ms is null then null else greatest(p_buffer_ms,0) end,
    case when p_rebuffer_count is null then null else greatest(p_rebuffer_count,0) end,
    case when p_position_ms is null then null else greatest(p_position_ms,0) end,
    case when p_duration_ms is null then null else greatest(p_duration_ms,0) end,
    nullif(left(coalesce(p_error_code,''),240),''),coalesce(p_extra,'{}'::jsonb)
  );
end;
$$;

revoke all on function public.record_video_playback_event(text,text,uuid,text,text,text,text,integer,integer,integer,integer,integer,integer,text,jsonb) from public;
grant execute on function public.record_video_playback_event(text,text,uuid,text,text,text,text,integer,integer,integer,integer,integer,integer,text,jsonb) to anon, authenticated;

create or replace view public.video_playback_hourly_summary as
select
  date_trunc('hour', created_at) as hour,
  platform,
  network_type,
  count(*) filter (where event_type='first_frame') as plays,
  round(avg(ttff_ms) filter (where event_type='first_frame')) as avg_ttff_ms,
  percentile_cont(0.95) within group (order by ttff_ms) filter (where event_type='first_frame') as p95_ttff_ms,
  count(*) filter (where event_type='rebuffer') as rebuffer_events,
  round(avg(buffer_ms) filter (where event_type='rebuffer')) as avg_rebuffer_ms,
  count(*) filter (where event_type='playback_error') as playback_errors
from public.video_playback_events
group by 1,2,3;

revoke all on public.video_playback_hourly_summary from anon, authenticated;