-- Migration-history marker.
-- The final conservative semantic packs are consolidated into
-- 20260830054000_local_brain_auto_tags_priority_control.sql for clean installs.
-- Production applied this version as an incremental precision step.
