import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutter_swipes/src/core/constants/listing_taxonomies.dart';
import 'package:flutter_swipes/src/core/theme/app_theme.dart';
import 'package:flutter_swipes/src/features/dashboard/domain/bento_media_pools.dart';
import 'package:flutter_swipes/src/features/dashboard/presentation/providers/discovery_location_provider.dart';
import 'package:flutter_swipes/src/core/routing/app_paths.dart';
import 'package:flutter_swipes/src/features/dashboard/presentation/widgets/ai_search_bar.dart';
import 'package:flutter_swipes/src/features/dashboard/presentation/widgets/events_teaser_card.dart';
import 'package:flutter_swipes/src/features/dashboard/presentation/widgets/quick_filter_media.dart';
import 'package:flutter_swipes/src/core/providers/visual_theme_provider.dart';
import 'package:flutter_swipes/src/features/map/presentation/screens/live_map_screen.dart';
import 'package:flutter_swipes/src/features/swipes/presentation/utils/open_swipe_deck.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';

class BentoDashboardScreen extends ConsumerWidget {
  const BentoDashboardScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final location = ref.watch(discoveryLocationProvider);
    final isLight = ref.watch(isLightThemeProvider);

    return Scaffold(
      backgroundColor: AppTheme.canvasFor(isLight: isLight),
      body: SafeArea(
        bottom: false,
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const AiSearchBar(),
                  const SizedBox(height: 8),
                  Text(
                    '✨ AI-powered · Answers are generated by AI. AI can make mistakes. Consider verifying important information.',
                    style: GoogleFonts.plusJakartaSans(
                      color: isLight
                          ? Colors.black.withAlpha(110)
                          : Colors.white38,
                      fontSize: 10,
                      height: 1.3,
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              child: Row(
                children: [
                  Expanded(
                    child: _FilterPill(
                      icon: Icons.location_on_rounded,
                      text: location.label,
                      wash: const Color(0xFFFF6B6B),
                      onTap: () => _pickCity(context, ref),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: _FilterPill(
                      icon: Icons.calendar_today_rounded,
                      text: location.dateLabel,
                      wash: const Color(0xFF4DABF7),
                      onTap: () => _pickDates(context, ref),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: _FilterPill(
                      icon: Icons.people_alt_rounded,
                      text:
                          '${location.guests} guest${location.guests == 1 ? '' : 's'}',
                      wash: const Color(0xFFFFD43B),
                      onTap: () => _pickGuests(context, ref),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 8),
            Expanded(
              child: MasonryGridView.count(
                crossAxisCount: 2,
                mainAxisSpacing: 10,
                crossAxisSpacing: 10,
                padding: const EdgeInsets.symmetric(horizontal: 16)
                    .copyWith(bottom: 120),
                itemCount: _bentoItems.length,
                itemBuilder: (context, index) {
                  final item = _bentoItems[index];
                  if (item.id == 'events') {
                    return SizedBox(
                      height: item.height,
                      child: EventsTeaserCard(
                        onTap: () => context.go(AppPaths.exploreEvents),
                      ),
                    );
                  }
                  return _BentoCard(
                    title: item.title,
                    subtitle: item.subtitle,
                    height: item.height,
                    media: BentoMediaPools.forId(item.id),
                    stagger: Duration(milliseconds: 400 * index),
                    // Only the first couple tiles decode video — web chokes
                    // when every bento cell spins up an HTML5 player.
                    enableVideo: index < 2,
                    onTap: () => _openBento(context, ref, item.id, item.title),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _openBento(
    BuildContext context,
    WidgetRef ref,
    String id,
    String title,
  ) {
    HapticFeedback.lightImpact();
    switch (id) {
      case 'legal':
        context.go(AppPaths.clientLegal);
        return;
      case 'seekers':
        context.go(AppPaths.exploreSeekers);
        return;
      case 'premium':
        context.push(AppPaths.subscriptionPackages);
        return;
      case 'video_tours':
        context.push(AppPaths.exploreTours);
        return;
      case 'roommates':
        context.push(AppPaths.exploreRoommates);
        return;
      case 'intel':
        context.push(AppPaths.exploreIntel);
        return;
      case 'prices':
        context.push(AppPaths.explorePrices);
        return;
      case 'services':
        context.push(AppPaths.clientServices);
        return;
      default:
        openClientSwipeDeck(
          context,
          categoryId: id,
          categoryTitle: title,
        );
    }
  }

  Future<void> _pickCity(BuildContext context, WidgetRef ref) async {
    final city = await showModalBottomSheet<String>(
      context: context,
      backgroundColor: AppTheme.dashElevated,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      builder: (context) {
        return SafeArea(
          child: ListView(
            padding: const EdgeInsets.fromLTRB(20, 20, 20, 32),
            children: [
              Text('CHOOSE CITY',
                  style: AppTheme.displayItalic.copyWith(fontSize: 18)),
              const SizedBox(height: 8),
              ListTile(
                leading:
                    const Icon(Icons.map_rounded, color: AppTheme.brandPrimary),
                title: const Text('Open live map',
                    style: TextStyle(color: Colors.white)),
                onTap: () {
                  Navigator.pop(context);
                  Navigator.of(context).push(
                    MaterialPageRoute(builder: (_) => const LiveMapScreen()),
                  );
                },
              ),
              const Divider(color: Colors.white24),
              for (final city in ListingTaxonomies.popularCities)
                ListTile(
                  title: Text(city, style: const TextStyle(color: Colors.white)),
                  onTap: () => Navigator.pop(context, city),
                ),
            ],
          ),
        );
      },
    );
    if (city != null) {
      ref.read(discoveryLocationProvider.notifier).setCity(city);
    }
  }

  Future<void> _pickDates(BuildContext context, WidgetRef ref) async {
    const options = [
      'Any date',
      'This weekend',
      'Next week',
      'This month',
      'Flexible',
    ];
    final picked = await showModalBottomSheet<String>(
      context: context,
      backgroundColor: AppTheme.dashElevated,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      builder: (context) {
        return SafeArea(
          child: ListView(
            padding: const EdgeInsets.fromLTRB(20, 20, 20, 32),
            shrinkWrap: true,
            children: [
              Text('WHEN', style: AppTheme.displayItalic.copyWith(fontSize: 18)),
              const SizedBox(height: 8),
              for (final option in options)
                ListTile(
                  title:
                      Text(option, style: const TextStyle(color: Colors.white)),
                  onTap: () => Navigator.pop(context, option),
                ),
            ],
          ),
        );
      },
    );
    if (picked != null) {
      ref.read(discoveryLocationProvider.notifier).setDateLabel(picked);
    }
  }

  Future<void> _pickGuests(BuildContext context, WidgetRef ref) async {
    var guests = ref.read(discoveryLocationProvider).guests;
    final confirmed = await showModalBottomSheet<int>(
      context: context,
      backgroundColor: AppTheme.dashElevated,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setModalState) {
            return SafeArea(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(24, 24, 24, 32),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('GUESTS',
                        style: AppTheme.displayItalic.copyWith(fontSize: 18)),
                    const SizedBox(height: 20),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        IconButton(
                          onPressed: () {
                            if (guests > 1) setModalState(() => guests -= 1);
                          },
                          icon: const Icon(Icons.remove_circle_outline,
                              color: Colors.white, size: 32),
                        ),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 24),
                          child: Text(
                            '$guests',
                            style: GoogleFonts.plusJakartaSans(
                              color: Colors.white,
                              fontSize: 40,
                              fontWeight: FontWeight.w900,
                            ),
                          ),
                        ),
                        IconButton(
                          onPressed: () {
                            if (guests < 16) setModalState(() => guests += 1);
                          },
                          icon: const Icon(Icons.add_circle_outline,
                              color: Colors.white, size: 32),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    SizedBox(
                      width: double.infinity,
                      child: FilledButton(
                        onPressed: () => Navigator.pop(context, guests),
                        style: FilledButton.styleFrom(
                          backgroundColor: AppTheme.brandPrimary,
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                          ),
                        ),
                        child: const Text('Done'),
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
    if (confirmed != null) {
      ref.read(discoveryLocationProvider.notifier).setGuests(confirmed);
    }
  }
}

class _FilterPill extends StatelessWidget {
  const _FilterPill({
    required this.icon,
    required this.text,
    required this.wash,
    required this.onTap,
  });

  final IconData icon;
  final String text;
  final Color wash;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        HapticFeedback.lightImpact();
        onTap();
      },
      child: Container(
        height: 40,
        decoration: BoxDecoration(
          color: const Color.fromRGBO(14, 14, 20, 0.96),
          borderRadius: BorderRadius.circular(999),
          border: Border.all(color: Colors.white, width: 1.5),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              padding: const EdgeInsets.all(4),
              decoration: BoxDecoration(
                color: wash.withAlpha(50),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, size: 14, color: wash),
            ),
            const SizedBox(width: 6),
            Flexible(
              child: Text(
                text,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                ),
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _BentoCard extends StatelessWidget {
  const _BentoCard({
    required this.title,
    required this.subtitle,
    required this.height,
    required this.media,
    required this.stagger,
    required this.onTap,
    this.enableVideo = true,
  });

  final String title;
  final String subtitle;
  final double height;
  final List<String> media;
  final Duration stagger;
  final VoidCallback onTap;
  final bool enableVideo;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        height: height,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(32),
          color: const Color.fromRGBO(22, 22, 28, 1),
          border: Border.all(color: Colors.transparent, width: 1.5),
        ),
        clipBehavior: Clip.antiAlias,
        child: Stack(
          fit: StackFit.expand,
          children: [
            QuickFilterMedia(
              sources: media,
              animationDelay: stagger,
              enableVideo: enableVideo,
            ),
            const DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [Color(0x22000000), Color(0xCC000000)],
                ),
              ),
            ),
            Positioned(
              bottom: 16,
              left: 16,
              right: 16,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.w900,
                      letterSpacing: 1,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    subtitle,
                    style: TextStyle(
                      color: Colors.white.withAlpha(220),
                      fontSize: 12,
                    ),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _BentoItemData {
  const _BentoItemData(this.id, this.title, this.subtitle, this.height);
  final String id;
  final String title;
  final String subtitle;
  final double height;
}

/// Cap `BENTO_ITEMS` order / sizes.
const _bentoItems = [
  _BentoItemData('property', 'PROPERTIES', 'Find properties to buy or rent', 260),
  _BentoItemData('events', 'EVENTS LIVE', 'Swipe event videos · tap to open', 340),
  _BentoItemData(
      'recommended', 'RECOMMENDED FOR YOU', 'Curated listings', 260),
  _BentoItemData(
      'services', 'WORKERS', 'Find people offering services', 340),
  _BentoItemData('popular', 'POPULAR', 'Trending now', 260),
  _BentoItemData(
      'yacht', 'YACHTS', 'Yachts & boats to charter or buy', 340),
  _BentoItemData(
      'motorcycle', 'MOTORCYCLES', 'Motorcycles for sale or rent', 340),
  _BentoItemData('bicycle', 'BICYCLES', 'Bicycles for sale or rent', 260),
  _BentoItemData('seekers', 'SEEKERS', 'People looking for workers', 260),
  _BentoItemData('legal', 'LEGAL SERVICES', 'Hire a top tier lawyer', 340),
  _BentoItemData('premium', 'PREMIUM', 'Buy a package & get benefits', 260),
];
